micronaut:
  application:
    name: profile
  server:
    port: 1020
    maxRequestSize: 5GB
    multipart:
      maxFileSize: 5GB
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    token:
      jwt:
        enabled: true
        generator:
          access-token-expiration: 3600
          refresh-token-expiration: 172800
        signatures:
          secret:
            generator:
              jws-algorithm: HS256
              secret: ${JWT_GENERATOR_SECRET:pleaseChangeThisSecretForANewOne}
  extensions:
    client:
      uri: ${ROUTING_URI:`http://localhost:1020`}

jpa:
  default:
    packages-to-scan:
      - 'com.pth.iflow.profile.entities'

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/profile`}?ApplicationName=app-profile-pool
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    username: ${JDBC_USER:iflow}
    password: ${JDBC_PASSWORD:iflow}
    validation-query: select 1

endpoints:
  info:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
  routes:
    enabled: false
    sensitive: false
  caches:
    enabled: false
    sensitive: false
  env:
    enabled: false
    sensitive: false
  threaddump:
    enabled: true
    sensitive: true
  logthreaddump:
    enabled: true
    sensitive: true
