micronaut:
  application:
    name: profile
  server:
    port: 1020
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              #jws-algorithm: HS256
              secret: ${JWT_GENERATOR_SECRET:pthifloepth}
        generator:
          refresh-token:
            secret: ${JWT_GENERATOR_SECRET:pthifloepth}
  extensions:
    securities:
      passwordpepper: passwordpepper

jpa:
  default:
    packages-to-scan:
      - 'com.pth.profile.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        format_sql: true

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/profile`}?ApplicationName=profile-pool
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    username: ${JDBC_USER:iflow}
    password: ${JDBC_PASSWORD:iflow}
  h2:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
