micronaut:
  application:
    name: gui
  server:
    port: 1200

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"

  views:
    folder: templates
    thymeleaf:
      enabled: true
      character-encoding: UTF-8
      template-mode:
        thymeleaf:
          suffix: .html
          prefix: /templates


  extensions:
    project: gui
    securities:
      passwordpepper: passwordpepper

