iflow:
  gui:
    uploadfile:
      temp-base-dir: c:/upload/temp
      archive-base-dir: c:/upload/archive
    cli-port: 4200
    cli-server: "http://localhost:4200"
    tesseract:
      tess-data-path: C:/tessdata

micronaut:
  application:
    name: gui
  server:
    port: 1200
    max-request-size: 100MB
    max-file-size: 100MB
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  cors:
    enabled: true
    single-header: true
    configurations:
      web:
        allowCredentials: true
        allowedHeaders:
          - Origin
          - Host
          - Authorization
          - Content-Type
          - Accept
          - X-PINGOTHER
          - Set-Cookie
          - Pragma
          - Cache-Control
          - Content-disposition
        allowedOrigins:
          - ${iflow.gui.cli-server}
        allowedMethods:
          - OPTIONS
          - POST
          - PUT
          - GET
          - DELETE
        exposedHeaders:
          - Access-Control-Allow-Origin
          - Access-Control-Allow-Headers
          - Access-Control-Request-Method
          - Access-Control-Request-Headers
          - Origin
          - Cache-Control
          - Content-Type
          - Authorization
          - Set-Cookie
          - myxyz

  security:
    enabled: true
    intercept-url-map:
      - pattern: /css/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /js/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /images/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /scripts/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /assets/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /auth/authenticate
        httpMethod: POST
        access:
          - isAnonymous()
      - pattern: /auth/login
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /auth/login
        httpMethod: POST
        access:
          - isAnonymous()
      - pattern: /auth/logout
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /auth/logout
        httpMethod: POST
        access:
          - isAnonymous()
      - pattern: /websocket/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /users/data/sessiondata
        httpMethod: GET
        access:
          - isAnonymous()
    token:
      jwt:
        #enabled: true
        generator:
          access-token-expiration: 7200
          refresh-token-expiration: 172800
        signatures:
          secret:
            generator:
              jws-algorithm: HS256
              secret: ${JWT_GENERATOR_SECRET:pleaseChangeThisSecretForANewOne}

    endpoints:
      login:
        enabled: true
        path: /auth/login
      logout:
        enabled: true
        path: /auth/logout
        get-allowed: true
      oauth:
        enabled: true
    session:
      enabled: true
      login-success-target-url: /users/data/sessiondata
      login-failure-target-url: /auth/authFailed
      #logout-targetUrl: '/auth/logout'
      #login-targetUrl: '/auth/authenticate'
#      unauthorized-target-url: '/auth/login'

  session:
    http:
      cookie-path: /
      cookie-name: iflow


  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"

  views:
    folder: templates
    thymeleaf:
      enabled: true
      character-encoding: UTF-8
      suffix: .html
      template-mode:
        thymeleaf:
          suffix: .html
          prefix: /templates


  extensions:
    project: gui
    securities:
      passwordpepper: passwordpepper

