micronaut:
  application:
    name: core
  server:
    port: 1010
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    token:
      jwt:
        enabled: true
        generator:
          access-token-expiration: 3600
          refresh-token-expiration: 172800
        signatures:
          secret:
            generator:
              jws-algorithm: HS256
              secret: ${JWT_GENERATOR_SECRET:pleaseChangeThisSecretForANewOne}

  extensions:
    project: core
    securities:
      passwordpepper: passwordpepper

jpa:
  default:
    name: 'default'
    packages-to-scan:
      - 'com.pth.core.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        format_sql: true

datasources:
  default:
    name: 'default'
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/core`}?ApplicationName=core-pool
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    username: ${JDBC_USER:iflow}
    password: ${JDBC_PASSWORD:iflow}
    pool-name: profile-pool
